version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (none required)"
  build:
    commands:
      - echo "Build started"
  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync frontend/ s3://cloud-notes-frontend-noman --delete

artifacts:
  files:
    - '**/*'

